CI: simplify syntax

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -15,15 +15,17 @@ jobs:
       - run:
           name: Tests
           command: |
-            errcount=0; \
-            for f in tests/*.sh; do printf "$f\t\t" && bash "$f" -H; \
-              status=$?; \
-              if [ $status -ne 0 ]; then \
-                errcount="$(($errcount+1))"; \
-              fi; \
-            done; \
-            if [ $errcount -ne 0 ]; then \
-              >&2 echo "Oh no! $errcount tests failed"; \
-              exit 1; \
+            errcount=0
+            for f in tests/*.sh; do
+              printf "$f\t\t"
+              bash "$f" -H
+              status=$?
+              if [ $status -ne 0 ]; then
+                errcount="$(($errcount+1))"
+              fi
+            done
+            if [ $errcount -ne 0 ]; then
+              >&2 echo "Oh no! $errcount tests failed"
+              exit 1
             fi
 
